# utils.py
# Type colors for visual representation
type_colors = {
    "normal": "#A8A77A",
    "fire": "#EE8130",
    "water": "#6390F0",
    "electric": "#F7D02C",
    "grass": "#7AC74C",
    "ice": "#96D9D6",
    "fighting": "#C22E28",
    "poison": "#A33EA1",
    "ground": "#E2BF65",
    "flying": "#A98FF3",
    "psychic": "#F95587",
    "bug": "#A6B91A",
    "rock": "#B6A136",
    "ghost": "#735797",
    "dragon": "#6F35FC",
    "dark": "#705746",
    "steel": "#B7B7CE",
    "fairy": "#D685AD"
}





# # utils.py
# # Pokemon type colors
# type_colors = {
#     "normal": "#A8A878",
#     "fire": "#F08030",
#     "water": "#6890F0",
#     "electric": "#F8D030",
#     "grass": "#78C850",
#     "ice": "#98D8D8",
#     "fighting": "#C03028",
#     "poison": "#A040A0",
#     "ground": "#E0C068",
#     "flying": "#A890F0",
#     "psychic": "#F85888",
#     "bug": "#A8B820",
#     "rock": "#B8A038",
#     "ghost": "#705898",
#     "dragon": "#7038F8",
#     "dark": "#705848",
#     "steel": "#B8B8D0",
#     "fairy": "#EE99AC"
# }

# # List of legendary Pokemon
# legendary_list = [
#     "articuno", "zapdos", "moltres", "mewtwo", "mew", "raikou", "entei", "suicune",
#     "lugia", "ho-oh", "celebi", "regirock", "regice", "registeel", "latias", "latios",
#     "kyogre", "groudon", "rayquaza", "jirachi", "deoxys", "uxie", "mesprit", "azelf",
#     "dialga", "palkia", "heatran", "regigigas", "giratina", "cresselia", "darkrai",
#     "shaymin", "arceus", "victini", "cobalion", "terrakion", "virizion", "tornadus",
#     "thundurus", "reshiram", "zekrom", "landorus", "kyurem", "keldeo", "meloetta",
#     "genesect", "xerneas", "yveltal", "zygarde", "diancie", "hoopa", "volcanion",
#     "tapu koko", "tapu lele", "tapu bulu", "tapu fini", "cosmog", "cosmoem", "solgaleo",
#     "lunala", "necrozma", "magearna", "marshadow", "zeraora", "meltan", "melmetal",
#     "zacian", "zamazenta", "eternatus", "kubfu", "urshifu", "zarude", "regieleki",
#     "regidrago", "glastrier", "spectrier", "calyrex"
# ]

# # Special form handling - map common names to API names
# special_forms = {
#     "deoxys": "deoxys-normal",
#     "deoxys normal": "deoxys-normal",
#     "deoxys attack": "deoxys-attack",
#     "deoxys defense": "deoxys-defense",
#     "deoxys speed": "deoxys-speed",
#     "giratina": "giratina-altered",
#     "giratina altered": "giratina-altered",
#     "giratina origin": "giratina-origin",
#     "shaymin": "shaymin-land",
#     "shaymin land": "shaymin-land",
#     "shaymin sky": "shaymin-sky",
#     "wormadam": "wormadam-plant",
#     "wormadam plant": "wormadam-plant",
#     "wormadam sandy": "wormadam-sandy",
#     "wormadam trash": "wormadam-trash",
#     "castform": "castform-normal",
#     "castform normal": "castform-normal",
#     "castform sunny": "castform-sunny",
#     "castform rainy": "castform-rainy",
#     "castform snowy": "castform-snowy",
#     "cherrim": "cherrim-overcast",
#     "cherrim overcast": "cherrim-overcast",
#     "cherrim sunshine": "cherrim-sunshine",
#     "darmanitan": "darmanitan-standard",
#     "darmanitan standard": "darmanitan-standard",
#     "darmanitan zen": "darmanitan-zen",
#     "tornadus": "tornadus-incarnate",
#     "tornadus incarnate": "tornadus-incarnate",
#     "tornadus therian": "tornadus-therian",
#     "thundurus": "thundurus-incarnate",
#     "thundurus incarnate": "thundurus-incarnate",
#     "thundurus therian": "thundurus-therian",
#     "landorus": "landorus-incarnate",
#     "landorus incarnate": "landorus-incarnate",
#     "landorus therian": "landorus-therian",
#     "keldeo": "keldeo-ordinary",
#     "keldeo ordinary": "keldeo-ordinary",
#     "keldeo resolute": "keldeo-resolute",
#     "meloetta": "meloetta-aria",
#     "meloetta aria": "meloetta-aria",
#     "meloetta pirouette": "meloetta-pirouette",
#     "aegislash": "aegislash-shield",
#     "aegislash shield": "aegislash-shield",
#     "aegislash blade": "aegislash-blade",
#     "pumpkaboo": "pumpkaboo-average",
#     "pumpkaboo average": "pumpkaboo-average",
#     "pumpkaboo small": "pumpkaboo-small",
#     "pumpkaboo large": "pumpkaboo-large",
#     "pumpkaboo super": "pumpkaboo-super",
#     "gourgeist": "gourgeist-average",
#     "gourgeist average": "gourgeist-average",
#     "gourgeist small": "gourgeist-small",
#     "gourgeist large": "gourgeist-large",
#     "gourgeist super": "gourgeist-super",
#     "zygarde": "zygarde-50",
#     "zygarde 50": "zygarde-50",
#     "zygarde 10": "zygarde-10",
#     "zygarde complete": "zygarde-complete",
#     "lycanroc": "lycanroc-midday",
#     "lycanroc midday": "lycanroc-midday",
#     "lycanroc midnight": "lycanroc-midnight",
#     "lycanroc dusk": "lycanroc-dusk",
#     "wishiwashi": "wishiwashi-solo",
#     "wishiwashi solo": "wishiwashi-solo",
#     "wishiwashi school": "wishiwashi-school",
#     "minior": "minior-red-meteor",
#     "minior meteor": "minior-red-meteor",
#     "minior core": "minior-red",
#     "mimikyu": "mimikyu-disguised",
#     "mimikyu disguised": "mimikyu-disguised",
#     "mimikyu busted": "mimikyu-busted",
#     "toxtricity": "toxtricity-amped",
#     "toxtricity amped": "toxtricity-amped",
#     "toxtricity low key": "toxtricity-low-key",
#     "eiscue": "eiscue-ice",
#     "eiscue ice": "eiscue-ice",
#     "eiscue noice": "eiscue-noice",
#     "indeedee": "indeedee-male",
#     "indeedee male": "indeedee-male",
#     "indeedee female": "indeedee-female",
#     "morpeko": "morpeko-full-belly",
#     "morpeko full belly": "morpeko-full-belly",
#     "morpeko hangry": "morpeko-hangry",
#     "urshifu": "urshifu-single-strike",
#     "urshifu single strike": "urshifu-single-strike",
#     "urshifu rapid strike": "urshifu-rapid-strike",
#     "calyrex": "calyrex",
#     "calyrex ice": "calyrex-ice",
#     "calyrex shadow": "calyrex-shadow",
# }